import {
  lev,
  barbos,
  sirius,
  purina,
  pethelp,
  happypaw,
  lico,
  josera,
  whiskas,
} from 'images';

export const ourFriends = [
  {
    id: 1,
    name: 'ЛКП "ЛЕВ"',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: lev,
  },
  {
    id: 2,
    name: 'Барбос',
    time: '8:00 - 20:00',
    address: 'Grigorenka Street, 56',
    email: 'barbos@gmail.com',
    phone: '066 488 0480',
    image: barbos,
  },
  {
    id: 3,
    name: 'Whiskas',
    time: 'day and night',
    address: 'website only',
    email: 'whiskas@gmail.com',
    phone: '0–800–500–155',
    image: whiskas,
  },
  {
    id: 4,
    name: 'Happy Paw',
    time: '9:00 - 19:00',
    address: 'Chota Rystaveli Street, 44',
    email: 'hello@happypaw.ua',
    phone: '+380 44 290-03-29',
    image: happypaw,
  },
  {
    id: 5,
    name: 'PetHelp',
    time: 'day and night',
    address: 'website only',
    email: 'pithelp.ukr@gmail.com',
    phone: 'email only',
    image: pethelp,
  },
  {
    id: 6,
    name: 'Сіріус',
    time: '11:00 - 16:00',
    address: 'Fedorivka, Kyiv Oblast',
    email: 'dogcat.sirius@gmail.com',
    phone: '+38 093 193 40 69',
    image: sirius,
  },
  {
    id: 7,
    name: 'PURINA',
    time: 'day and night',
    address: 'website only',
    email: 'info@ua.nestle.com',
    phone: '1-800-778-7462',
    image: purina,
  },
  {
    id: 8,
    name: 'Josera',
    time: '9:00 - 17:00',
    address: 'Sholom-Aleikhema St, 11',
    email: 'info@josera.ua',
    phone: '0800 409 060',
    image: josera,
  },
  {
    id: 9,
    name: 'LICO',
    time: '9:00 - 20:00',
    address: 'Dryhetiv Street, 77',
    email: 'lico@gmail.com',
    phone: '+38 097 509 8005',
    image: lico,
  },
];
