import {
  lev,
  barbos,
  sirius,
  purina,
  pethelp,
  happypaw,
  lico,
  josera,
  whiskas,
} from 'images';

export const ourFriends = [
  {
    id: 1,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: lev,
  },
  {
    id: 2,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: barbos,
  },
  {
    id: 3,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: whiskas,
  },
  {
    id: 4,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: happypaw,
  },
  {
    id: 5,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: pethelp,
  },
  {
    id: 6,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: sirius,
  },
  {
    id: 7,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: purina,
  },
  {
    id: 8,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: josera,
  },
  {
    id: 9,
    name: 'ЛКП "ЛЕВ',
    time: '8:00 - 19:00',
    address: 'Promuslova Street, 56',
    email: 'lkplev@gmail.com',
    phone: '(032) 293-30-41',
    image: lico,
  },
];
